set_property IOSTANDARD LVCMOS18 [get_ports {CCW[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CCW[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CCW[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CCW[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CW[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CW[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CW[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CW[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {direction[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {direction[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {direction[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PWM_out[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PWM_out[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PWM_out[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PWM_out[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {speed[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {speed[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {speed[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {speed[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {speed[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property PACKAGE_PIN W5 [get_ports clk]

create_clock -period 10.000 -name clock -waveform {0.000 5.000} [get_ports clk]

set_property PACKAGE_PIN W15 [get_ports {speed[4]}]
set_property PACKAGE_PIN W17 [get_ports {speed[3]}]
set_property PACKAGE_PIN W16 [get_ports {speed[2]}]
set_property PACKAGE_PIN V16 [get_ports {speed[1]}]
set_property PACKAGE_PIN V17 [get_ports {speed[0]}]
set_property PACKAGE_PIN H1 [get_ports {PWM_out[1]}]
set_property PACKAGE_PIN A15 [get_ports {PWM_out[0]}]
set_property PACKAGE_PIN A17 [get_ports {CW[0]}]
set_property PACKAGE_PIN C15 [get_ports {CCW[0]}]
set_property PACKAGE_PIN R2 [get_ports {direction[2]}]
set_property PACKAGE_PIN T1 [get_ports {direction[1]}]
set_property PACKAGE_PIN U1 [get_ports {direction[0]}]

set_property PACKAGE_PIN J1 [get_ports {PWM_out[3]}]

set_property PACKAGE_PIN L2 [get_ports {CW[3]}]
set_property PACKAGE_PIN A16 [get_ports {CW[2]}]
set_property PACKAGE_PIN J2 [get_ports {CCW[3]}]
set_property PACKAGE_PIN B15 [get_ports {CCW[2]}]

set_property PACKAGE_PIN A14 [get_ports {PWM_out[2]}]
set_property PACKAGE_PIN K2 [get_ports {CW[1]}]
set_property PACKAGE_PIN H2 [get_ports {CCW[1]}]


set_property IOSTANDARD LVCMOS18 [get_ports UART_in]
set_property PACKAGE_PIN B18 [get_ports UART_in]

set_property IOSTANDARD LVCMOS18 [get_ports {direction_temp[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {direction_temp[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {direction_temp[0]}]
set_property PACKAGE_PIN L1 [get_ports {direction_temp[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {speed_temp[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {speed_temp[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {speed_temp[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {speed_temp[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {speed_temp[0]}]
set_property PACKAGE_PIN P1 [get_ports {direction_temp[1]}]
set_property PACKAGE_PIN N3 [get_ports {direction_temp[0]}]
set_property PACKAGE_PIN P3 [get_ports {speed_temp[4]}]
set_property PACKAGE_PIN U3 [get_ports {speed_temp[3]}]
set_property PACKAGE_PIN W3 [get_ports {speed_temp[2]}]
set_property PACKAGE_PIN V3 [get_ports {speed_temp[1]}]
set_property PACKAGE_PIN V13 [get_ports {speed_temp[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports from_sensor]
set_property IOSTANDARD LVCMOS18 [get_ports to_sensor]
set_property IOSTANDARD LVCMOS18 [get_ports UART_out]
set_property PACKAGE_PIN K17 [get_ports to_sensor]
set_property PACKAGE_PIN M18 [get_ports from_sensor]
set_property PACKAGE_PIN A18 [get_ports UART_out]
